
stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: gideontee/gitlab-demo
  IMAGE_TAG: flask-app-v1

run_tests:
  image: python:3.9-slim-buster
  stage: test
  before_script:
    - apt-get update
    - apt-get install make -y
  script:
    - make test

build_image:
  image: docker:28.0.4-cli
  stage: build
  services:
    - name: docker:28.0.4-dind
      alias: docker

  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: unix:///var/run/docker.sock  # Use host Docker

  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

  script:
    - docker build -f build/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  variables:
    SERVER_IP: 184.72.122.179
  before_script:
    - chmod 400 $SSH_PEM
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PEM ubuntu@$SERVER_IP "
      docker login -u $DOCKER_USER -p $DOCKER_PASS &&
      docker run -d -p 5000:5000 --rm --name flask_server $IMAGE_NAME:$IMAGE_TAG
      "