
stages:
  - test
  - build


run_tests:
  image: python:3.9-slim-buster
  stage: test
  before_script:
    - apt-get update
    - apt-get install make -y
  script:
    - make test

build_image:
  image: docker:28.0.4-cli
  stage: build
  services:
    - docker:28.0.4-dind

  variables:
    IMAGE_NAME: gideontee/gitlab-demo
    IMAGE_TAG: flask-app-v1
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS

  script:
    - docker build -f build/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG