#version: '3.8'

services:
  gitlab-server:
    image: 'gitlab/gitlab-ce'
    container_name: 'gitlab-container'
    environment:
      GITLAB_ROOT_USERNAME: 'root'
      GITLAB_ROOT_PASSWORD: 'Gideon@777'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'
        nginx['listen_port'] = 8000

    ports:
      - '8000:8000'

    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    privileged: true # required for dind
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
    networks:
      - gitlab-network

  dind:
    image: docker:28.0.4-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=''
    networks:
      - gitlab-network

volumes:
  gitlab_config:
    external: true
  gitlab_data:
    external: true
  gitlab_logs:
    external: true
  gitlab-runner-config:
    external: true



networks:
  gitlab-network:
    driver: bridge